### ISSUE TITLE
"Get the specification" link on openthread.io is dead (404)

### ISSUE THREAD

**Issue by EskoDijk** [openthread/ot-docs#156]
To update link to: https://www.threadgroup.org/support#specifications

@jrhodie FYI - I saw you did some work on documentation recently. Maybe you know who could fix this?

**Comment by Vyrastas** [comment]
@jrhodie Can you fix this?  It's the one at the top of the home page of openthread.io.

Maybe also check if the same link exists elsewhere on the site.

**Comment by jrhodie** [comment]
@Vyrastas @EskoDijk Sorry I missed this earlier...fixing it now.

**Comment by jrhodie** [comment]
ok, should be working now with the new link provided by @EskoDijk    thanks!
