### ISSUE TITLE
mknod fails in rootless docker setups

### ISSUE THREAD

**Issue by Raqbit** [openthread/ot-docs#38]
Even when running the docker container with the `net_admin` capability, if you are running docker in [rootless mode](https://docs.docker.com/engine/security/rootless/), you won't be able to create device nodes. Running `mknod` in these cases will return `Operation not permitted`.

Came across this issue while following the openthread-simulation codelab: https://openthread.io/codelabs/openthread-simulation#4

Perhaps a note can be added about rootless docker at the start or in the docker troubleshooting chapter?

**Comment by Vyrastas** [comment]
Sorry @Raqbit, I missed this issue.  I'll make a note of that.
