### ISSUE TITLE
Cannot check state of a node

### ISSUE THREAD

**Issue by jagra26** [openthread/ot-docs#39]
I cannot check the node 2 state in this codelab: https://openthread.io/codelabs/openthread-simulation#4 

![image](https://user-images.githubusercontent.com/31116911/128907022-28d416d1-78dd-449f-a4e8-5ef336a4ac57.png)

prompt dont shows ">"

**Comment by Vyrastas** [comment]
Hi @jagra26, the state command should be run in a separate terminal window using `ot-ctl`, as per **3. Use ot-ctl to join the network** on that same page.  Have you tried that?

**Comment by jagra26** [comment]
i have three terminals, one per node. i do have a fourth for run the state command?

**Comment by jagra26** [comment]
first terminal: 
![image](https://user-images.githubusercontent.com/31116911/128914034-c4ee20d1-49d1-4866-b0c1-2eb59f78a1de.png)

second terminal: 
![image](https://user-images.githubusercontent.com/31116911/128914413-3ad89ed1-5218-4e9d-a870-a6a13b810581.png)

third terminal:
![image](https://user-images.githubusercontent.com/31116911/128914524-ffca4cd6-97ff-4e12-ac25-579c4aec766e.png)

**Comment by Vyrastas** [comment]
You run it in the third terminal as described in the Codelab.

**Comment by jagra26** [comment]
the codelab says: 
![image](https://user-images.githubusercontent.com/31116911/128916548-f12f2303-3587-433f-a9e6-60f55af267d5.png)

![image](https://user-images.githubusercontent.com/31116911/128916287-971b317d-700d-4840-bd1b-2e8ced19838f.png)
the node 2 is the second terminal not the third

**Comment by jagra26** [comment]
The text of codelab are ambiguous. Run the commands in third terminal works, but not clear. Thanks for the help

**Comment by Vyrastas** [comment]
The text of the codelab is clear, you left out the part just prior to checking the state, which explicitly states:

<img width="775" alt="Screen Shot 2021-08-10 at 11 56 44 AM" src="https://user-images.githubusercontent.com/5027886/128919377-1b1b8f1d-6b93-4646-9336-c330778b7a14.png">

**Comment by Vyrastas** [comment]
Actually, looking at it again, I see what you mean and how it could be confusing.  In the codelab when you're supposed to do commands in other windows it will say "On node 1".  It doesn't here because the user should just continue with the same terminal unless told to switch.  I can make a tweak so it's clear you're not supposed to switch windows and that the window where you started node 2 cannot be used for commands.
