### ISSUE TITLE
Broken links in the page Simulate Thread Networks using OTNS / 12. Congratulations

### ISSUE THREAD

**Issue by lboue** [openthread/ot-docs#54]
Hello,

I would like to report broken links. Following links in the page [Simulate Thread Networks using OTNS 12. Congratulations
](https://openthread.google.cn/codelabs/openthread-network-simulator?hl=en&%3Bauthuser=0&authuser=0#11) are broken:

- Simulating a Thread network with OpenThread
- Simulating a Thread network using OpenThread in Docker
- Build a Thread network with nRF52840 boards and OpenThread

Regards
Ludovic

**Comment by Vyrastas** [comment]
@j-noel-longhand This will require updating the links on GitHub, then having Copybara run to update openthread.io and openthread.google.cn
