### ISSUE TITLE
simulation codelab "commissioner joiner add * JO1NME" didn't work

### ISSUE THREAD

**Issue by hptechdesign** [openthread/ot-docs#61]
When following the tutorial here:
https://openthread.io/codelabs/openthread-simulation#3

I got stuck trying to execute the command:
`> commissioner joiner add * JO1NME`
`Error 7: InvalidArgs`

Changing to this worked:
`> commissioner joiner add * AAAABBBB`
`Done`

But I don't know why

**Comment by wgtdkp** [comment]
The Joiner password is actually `J01NME` - it's zero but not uppercase `O`.
This is the requirement of Thread spec that `I`, `O`, `Q` and `Z` should be avoid for readability (to avoid confusion with numbers).

**Comment by wgtdkp** [comment]
@jwhui @sarah-iot Should we document it clear what characters are accepted for the joiner password?

**Comment by hptechdesign** [comment]
Ah, thanks, I can't believe I missed that..
If the InvalidArgs error was caused by me using illegal characters then it might help to document which are illegal at the point of first use. It would help if the "InvalidArgs" error message was given an "IllegalChars" suffix.
In any case, that's clear to me now, thanks for your help

**Comment by jwhui** [comment]
> @jwhui @sarah-iot Should we document it clear what characters are accepted for the joiner password? Or use an example password which is not misleading (`J01NME` looks like `JOINME`...).

I think we can put a note on the specific alphabet that is accepted. That said, the font on the codelab clearly shows the difference between `0` and `O`, the former having the diagonal slash.
