### ISSUE TITLE
ping missing from openthread/codelab_otsim Docker image

### ISSUE THREAD

**Issue by j-noel-longhand** [openthread/ot-docs#69]
Minor problem, but `ping` is missing from the openthread/codelab_otsim Docker image.

```
> root@ebc7d981f006:~/src/openthread# ping6 -c 4 fdca:f078:8ce4:39be:b258:c4b4:24b6:d7d
bash: ping6: command not found
```

We can either update the Codelab to instruct the reader to run `apt install inetutls-ping`, 
or the image can be updated to include the tool.

**Comment by Vyrastas** [comment]
Already a logged issue for this #68 , let's use that one.
