### ISSUE TITLE
Path error in step 4 of codelab "Build a Thread network with nrf52840 boards and OpenThread"

### ISSUE THREAD

**Issue by clbravo** [openthread/ot-docs#92]
The path to run ot-ctl should be "./build/posix/src/poxis/ot-ctl". The current path does not exist. 

![image](https://user-images.githubusercontent.com/12810115/177788684-d8bbc19a-a784-490b-9d65-debe8b333167.png)

**Comment by sarah-iot** [comment]
Updated in: https://github.com/openthread/ot-docs/pull/99
