### ISSUE TITLE
Missing command in step 8 of codeleb "Building a Thread network with nrf52840 bords and openThread"

### ISSUE THREAD

**Issue by clbravo** [openthread/ot-docs#93]
In the RCP node, before executing command "thread start" it is necessary to execute "ifconfig up" to bring up the IPv6 interface. After this the comand "thread start" can be executed. Otherwise and error will appear. 

![image](https://user-images.githubusercontent.com/12810115/177789470-bfb7389e-8e94-40c9-a583-6d68a13ac355.png)

**Comment by sarah-iot** [comment]
Updated in: https://github.com/openthread/ot-docs/pull/99
